(TeX-add-style-hook
 "Nidish_Project"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "10pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "top=1in" "left=.75in" "right=.75in" "bottom=0.75in") ("babel" "USenglish")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "geometry"
    "babel"
    "times"
    "graphicx"
    "subcaption"
    "tikz"
    "hyperref"
    "amsmath"
    "amssymb"
    "cancel"
    "bm"
    "cleveref")
   (LaTeX-add-labels
    "sec:introduction"
    "sec:formulation"
    "fig:schem"
    "eq:def"
    "eq:defgrad"
    "eq:strain"
    "eq:strainexp"
    "eq:stress"
    "sec:stra-energy-dens"
    "eq:sedens"
    "eq:armoms"
    "eq:linsedens"
    "sec:kinet-energy-dens"
    "eq:kedens"
    "eq:linkedens"
    "eq:lageq"
    "sec:external-forcing"
    "fig:lds"
    "eq:nflw"
    "eq:nflvwrk"
    "eq:flwrk"
    "eq:flvwrk"
    "sec:boundary-conditions"
    "sec:finite-elem-form"
    "eq:isopar"
    "eq:ndofs"
    "eq:1"
    "eq:Lagtot"
    "eq:Le"
    "eq:femeom"
    "eq:dyneom"
    "sec:path-foll-bifurc"
    "eq:genalgeq"
    "eq:ALCNST"
    "eq:PALCNST"
    "eq:d3"
    "sec:dynam-stab-estim"
    "sec:valid-line-test"
    "fig:cbeam"
    "tab:physicalprops"
    "sec:note-shear-locking"
    "eq:sla"
    "fig:sla"
    "sec:stat-valid-test"
    "fig:staticval"
    "sec:low-amplitude-modal"
    "fig:lowampeig"
    "eq:longmodes"
    "eq:transmodes"
    "sec:nonl-appl-cases"
    "sec:follower-vs-non"
    "fig:followervsnonfollower"
    "sec:buckling-cant"
    "tab:bucklcrit"
    "fig:buckbif"
    "sec:buckl-simply-supp"
    "fig:simpsupp"
    "fig:buckbif_simpsupp"
    "sec:buckl-simply-supp-1"
    "fig:tipdefcsimpsuppbuck"
    "sec:snap-thro-behav"
    "fig:buck1"
    "fig:buck2"
    "fig:buck3"
    "fig:buck4"
    "sec:disc-concl"
    "sec:guide-subm-pyth"
    "sec:relv-funct-deriv"
    "eq:e0"
    "eq:g0"
    "eq:g0e"
    "eq:e1"
    "eq:e1fs"
    "eq:ep2"
    "sec:finite-elem-equat"
    "eq:eom"
    "eq:kedensred"
    "eq:fint"
    "eq:udiffs"
    "sec:third-grad-calc"))
 :latex)

